### ISSUE TITLE
Allow disabling thumbnail preview (also by default)

### ISSUE THREAD

**Issue by BigRoy** [Colorbleed/maya-capture-gui#10]
# Problem

The preview widget aids the artist to give an idea of the playblast outcome, nevertheless for very large and complex scenes it's unnecessarily slow because it will try to update on each option change that results in different output. Instead it would be easier for those scenes to allow the artist to update the preview only manually.

# Solution

Allow disabling the auto-updating feature of the thumbnail (and maybe even hide it to gain screen space?).

**Comment by aardschok** [comment]
_**Allow disabling the auto-updating feature of the thumbnail (and maybe even hide it to gain screen space?**_).
This is currently the case, after the user clicks preview the widget pops up but it will not auto-update when settings are changed.

_**Instead it would be easier for those scenes to allow the artist to update the preview only manually**._
Adding a preview state attribute to the preview widget which can be set by a checkbox, if checked it will be able refresh, if not it will return. 
Open for discussion : create error message box to warn the user if preview widget has been disable or just print the error. I opted for the first one.

_Note:_  I was not able to push the branch to this repository.

**Comment by aardschok** [comment]
Toggling display with checkbox works and does not refresh when toggled.
Implemented warning message when preview is disables and preview is clicked.
