### ISSUE TITLE
Retrieve filename + filepath from browse button when filename is similar to folder name

### ISSUE THREAD

**Issue by aardschok** [Colorbleed/maya-capture-gui#30]
Example : When clicking "browse" and creating a folder called "test" and insert "TEST" as filename returns the wrong directory while the filename is correct.

- Check what the file dialog actually returns
- Refactor code based on findings

**Comment by aardschok** [comment]
Image of user's error:
https://files.slack.com/files-pri/T031MLUJ7-F59D44WU8/pasted_image_at_2017_05_08_12_56.png

**Comment by aardschok** [comment]
@BigRoy this is has been resolved in with pull request #42 ?

**Comment by BigRoy** [comment]
Yes, this particular issue is fixed with #42
