### ISSUE TITLE
Maya fatal error when re-running the gui

### ISSUE THREAD

**Issue by BigRoy** [Colorbleed/maya-capture-gui#46]
# Problem

Maya sometimes crashes fatally when (re)running the gui.

To reproduce:

```python
import capture_gui

app = capture_gui.main()
app.close()
```

Run this code, run it again, and again, and again. Most likely within the first 20 runs Maya would have already crashed. I'm unable to quickly identify the exact source of the problem, woohoo, time for some debugging?

**Comment by aardschok** [comment]
Opened the crash log and found this python stack

```python

//Python stack:
  File: "<maya console>", line 11, in <module>()
  File: "C:\Users\User\Documents\development\maya-capture-gui\capture_gui\__init__.py", line 19, in main(show=True)
    parent = lib.get_maya_main_window()
  File: "C:\Users\User\Documents\development\maya-capture-gui\capture_gui\lib.py", line 367, in get_maya_main_window()
    for obj in QtWidgets.QApplication.topLevelWidgets():
```

Seems that we need to improve the get_maya_main_window() function

**Comment by BigRoy** [comment]
Interesting! @mottosso what do you think?

```python
import capture_gui.lib
import capture_gui.app
from Qt import QtWidgets

def get_maya_main_window():
    """Return Maya's main window"""
    widgets = QtWidgets.QApplication.topLevelWidgets()
    for obj in widgets:
        if obj.objectName() == 'MayaWindow':
            return obj


parent = get_maya_main_window()

# launch app
window = capture_gui.app.App(title="Capture GUI",
                             parent=parent)
    
window.show()
window.close()
```

This crashes.
Though this *does not*:

```python

import capture_gui.lib
import capture_gui.app
from Qt import QtWidgets
import maya.OpenMayaUI as omui
try:
    import shiboken
except ImportError:
    import shiboken2 as shiboken

def get_maya_main_window():

   """

   Get the main Maya window as a QtGui.QMainWindow instance

   :return: QtGui.QMainWindow instance of the top level Maya windows

   """
   ptr = omui.MQtUtil.mainWindow()
   if ptr is not None:
       return shiboken.wrapInstance(long(ptr), QtWidgets.QWidget)


parent = get_maya_main_window()

# launch app
window = capture_gui.app.App(title="Capture GUI",
                             parent=parent)
    
window.show()
window.close()
```

Interestingly enough there seems to be some issues with the top level widgets. Probably a pointer that gets garbage collected too early?

_More interestingly, running the second one in the same maya session after the first one makes it *not crash*. There's something in the first version that allows it to avoid the crash.

**Comment by mottosso** [comment]
Try replacing this:

```python
QtWidgets.QApplication.topLevelWidgets()
```

With this:

```python
QtWidgets.QApplication.instance().topLevelWidgets()
```

**Comment by aardschok** [comment]
Have replaced the line, new Maya and it is still crashing.
Down below is a crash log from Maya.

[MayaCrashLog17-05-10_10-29.txt](https://github.com/Colorbleed/maya-capture-gui/files/989198/MayaCrashLog17-05-10_10-29.txt)

**Comment by mottosso** [comment]
How about this?

```python
from Qt import QtWidgets

def get_maya_main_window():
    """Return Maya's main window"""
    app = QtWidgets.QApplication.instance()
    return {o.objectName(): o for o in app.topLevelWidgets()}["MayaWindow"]

parent = get_maya_main_window()

# launch app
window = capture_gui.app.App(title="Capture GUI",
                             parent=parent)
window.show()
window.close()
```

**Comment by BigRoy** [comment]
It seems to produce the same error. Though, interestingly enough, this works:

```python
from Qt import QtWidgets
import capture_gui.app

widgets = QtWidgets.QApplication.instance().topLevelWidgets()
parent = {o.objectName(): o for o in widgets}["MayaWindow"]

# launch app
window = capture_gui.app.App(title="Capture GUI",
                             parent=parent)
window.show()
window.close()
```

And this does not:

```python
from Qt import QtWidgets
import capture_gui.app

def get_maya_main_window():
    widgets = QtWidgets.QApplication.instance().topLevelWidgets()
    parent = {o.objectName(): o for o in widgets}["MayaWindow"]
    return parent

# launch app
window = capture_gui.app.App(title="Capture GUI",
                             parent=get_maya_main_window())
window.show()
window.close()
```

Note that when widgets isn't originally stored in the `widgets` variable it also crashes. (I'm testing this with Qt.py on PySide in Maya 2016 EXT1 SP6)

Whenever the `app` or `widgets` variable gets garbage collected things go haywire.

**Comment by mottosso** [comment]
I've encountered this before, where objects are garbage collected in the function, before being returned. This might be a bug in the binding.

**Comment by BigRoy** [comment]
Even though the problem is an interesting one because it was built in a way that we'd expected to just work a fix was implemented in https://github.com/Colorbleed/maya-capture-gui/commit/86651c865b5e347aad4d56fdb6a493e268ebdc82 by swapping to using `shiboken` (or `shiboken2`).

I'm closing this issue, but feel free to continue discussion on this interesting bug that was there.
