### ISSUE TITLE
Error "libshiboken" on linux

### ISSUE THREAD

**Issue by willDTF** [Colorbleed/maya-capture-gui#73]
Hi,
When I try to open the gui on centos 7.6 / maya 2019.1, the console return this errors

`RuntimeWarning: libshiboken: Overflow: Value -9223372036854775807 exceeds limits of type  [signed] "i" (4bytes)., at line 102, in "/mnt/Pipeline/Maya/scripts/capture_gui/plugins/timeplugin.py"
OverflowError
RuntimeWarning: libshiboken: Overflow: Value 9223372036854775807 exceeds limits of type  [signed] "i" (4bytes)., at line 102, in "/mnt/Pipeline/Maya/scripts/capture_gui/plugins/timeplugin.py"`

on windows it's works normally

**Comment by BigRoy** [comment]
@Kaiz3rTool this sounds like the same problem as https://github.com/Colorbleed/maya-capture-gui/issues/68 could you see if that workaround fixes it for you? 

If so, a PR would be more than welcome. I wonder why CentOS is giving trouble with it though. But if you are unfamiliar with Github/PRs I could set one up too.

**Comment by willDTF** [comment]
hi, sorry for the late answer
about the fix, do I need to replace all instance of sys.maxint or a specific one ?

**Comment by BigRoy** [comment]
Let me see if I can prepare a PR tomorrow for you too try.

I believe its line 102 and line 105: https://github.com/Colorbleed/maya-capture-gui/blob/master/capture_gui/plugins/timeplugin.py#L102

**Comment by willDTF** [comment]
hi, not working for me so I replaced all sys.maxint by 1 billion and it works (pretty sure I will never need to go that far ^^ )
thank you for your help
